### ISSUE TITLE
Trafic_Sign_Recognition issues

### ISSUE THREAD

**Issue by snping** [raviBhadeshiya/robotic_perception#14]
hello , I am a  chinese student, thank you share this code. I find a issues when I run matlab code. There is no folder named input in the trafic sign recognition project.

**Comment by raviBhadeshiya** [comment]
Dataset was big and it would be inefficient to upload.
But you can download it from http://benchmark.ini.rub.de/

**Comment by nr-parikh** [comment]
@snping I hope you found the data. Instead of using the link provided by @raviBhadeshiya, you can also use your own data.

**Comment by snping** [comment]
@raviBhadeshiya  I can't run the Trafic_Sign_Recognition code. I download GTSDB dataset, but I can't understand i value. I am a beginner. can you tell me how to run it ? thank you very much.

**Comment by raviBhadeshiya** [comment]
Find line that contain `image1=imread(sprintf('input/image.0%d.jpg',i));`  in` testNewMain.m.
Where `sprintf('input/image.0%d.jpg',13)`  means
> `input/image.013.jpg` 

or edit your code to read image frame by frame for your dataset and assign it to image1

**Comment by snping** [comment]
how to modify this issue?




------------------ 原始邮件 ------------------
发件人: "Ravi Bhadeshiya";<notifications@github.com>;
发送时间: 2017年8月30日(星期三) 凌晨5:38
收件人: "raviBhadeshiya/robotic_perception"<robotic_perception@noreply.github.com>; 
抄送: "老牛"<190907109@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [raviBhadeshiya/robotic_perception] Trafic_Sign_Recognitionissues (#14)




Find line that contain image1=imread(sprintf('input/image.0%d.jpg',i));  intestNewMain.m. Wheresprintf('input/image.0%d.jpg',13)`  means
  
input/image.013.jpg
  
or edit your code to read image frame by frame for your dataset and assign it to image1

**Comment by snping** [comment]
There is no directory named isModel, where can I find it ? and how to make this code run ? can you help me ? thank you very much.
------------------ 原始邮件 ------------------
发件人: "Ravi Bhadeshiya";<notifications@github.com>;
发送时间: 2017年8月30日(星期三) 凌晨5:38
收件人: "raviBhadeshiya/robotic_perception"<robotic_perception@noreply.github.com>; 
抄送: "老牛"<190907109@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [raviBhadeshiya/robotic_perception] Trafic_Sign_Recognitionissues (#14)




Find line that contain image1=imread(sprintf('input/image.0%d.jpg',i));  intestNewMain.m. Wheresprintf('input/image.0%d.jpg',13)`  means
  
input/image.013.jpg
  
or edit your code to read image frame by frame for your dataset and assign it to image1

**Comment by raviBhadeshiya** [comment]
Can you tell me which file are you trying to run? and post your error snapshot here! 
I don't think you need isModel  and FYI you can train your own cascade classifier.

**Comment by snping** [comment]
I want to study signs Recognition, So I ran all files. But the code is invalid.
 picture1
In timepass file , the error as picture1.


picture2
In testClassify file, the error as  picture2


And I can't understand the meaning of the whole code, can you give me a detailed document? thank you very much.






------------------ 原始邮件 ------------------
发件人: "Ravi Bhadeshiya";<notifications@github.com>;
发送时间: 2017年8月30日(星期三) 中午11:09
收件人: "raviBhadeshiya/robotic_perception"<robotic_perception@noreply.github.com>; 
抄送: "老牛"<190907109@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [raviBhadeshiya/robotic_perception] Trafic_Sign_Recognitionissues (#14)




Can you tell me which file are you trying to run? and post your error snapshot here!
 I don't think you need isModel  and FYI you can train your own cascade classifier.

**Comment by raviBhadeshiya** [comment]
try to run testNewMain ! and I can't see the picture!
